services:
  meetup.client:
    image: meetup.client
    container_name: meetup.client
    build:
      context: ./src/MeetUp-Client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - meetup-network
    depends_on:
      - meetup.api

  meetup.api:
    image: meetup.api
    container_name: meetup.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - .env
    build:
      context: .
      dockerfile: src/MeetUp.API/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - meetup.keycloak
      - meetup.db
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - meetup-network
      
  meetup.keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: meetup.keycloak
    env_file:
      - .env
    command: start-dev
    ports:
      - "8080:8080"
    volumes:
      - meetup_keycloak_data:/opt/keycloak/data
      - ./scripts:/opt/keycloak/data/import
    networks:
      - meetup-network
  
  meetup.db:
    image: postgres:latest
    container_name: meetup.db
    env_file:
      - .env
    volumes:
      - meetup_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - meetup-network
  
  meetup.livekit:
    image: livekit/livekit-server:latest
    container_name: meetup.livekit
    env_file:
      - .env
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
    environment:
      - LIVEKIT_CONFIG_FILE=/etc/livekit.yaml
      - LIVEKIT_REDIS_ADDRESS=meetup.redis:6379
    networks:
      - meetup-network

  egress:
    container_name: meetup.egress
    image: livekit/egress:latest
    cap_add:
      - SYS_ADMIN # Required for Chrome capture
    env_file:
      - .env
    volumes:
      - ./egress.yaml:/etc/egress.yaml
    environment:
      - EGRESS_CONFIG_FILE=/etc/egress.yaml
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}         # <--- REQUIRED
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} # <--- REQUIRED
      # If you use the LiveKit keys in yaml via ${...}, add them too:
      - LIVEKIT_API_KEY=${LIVEKIT__ApiKey}
      - LIVEKIT_API_SECRET=${LIVEKIT__ApiSecret}
    shm_size: 2g  
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - meetup-network

  redis:
    container_name: meetup.redis
    image: redis:7-alpine
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6379:6379"
    networks:
      - meetup-network

volumes:
  meetup_keycloak_data:
  meetup_postgres_data:

networks:
  meetup-network:
    driver: bridge
